name: Building and Testing
run-name: ${{ github.actor}} trigerred workflows

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build -x test

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Running application tests
        run: ./gradlew test

  checking-code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: yutailang0119/action-ktlint@v4
        with:
          report-path: build/*.xml
          ignore-warnings: true
        continue-on-error: false